"""merge Section 6 evidence library additions

Revision ID: 0b55a5033c01
Revises: b2c9a41f7e3d
Create Date: 2026-08-16 19:53:50.131952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b55a5033c01'
down_revision: Union[str, None] = 'b2c9a41f7e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_jobs',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('QUEUED', 'PARSING', 'TAGGING', 'EMBEDDING', 'COMPLETE', 'FAILED', name='job_stage'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_jobs_document_id'), 'index_jobs', ['document_id'], unique=False)
    op.add_column('chunks', sa.Column('category', sa.Enum('CASE_STUDY', 'METHODOLOGY', 'COMPANY_DOCUMENT', name='document_category'), nullable=False))
    op.add_column('chunks', sa.Column('phase', sa.String(length=255), nullable=False))
    op.add_column('chunks', sa.Column('image_paths', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_chunks_category'), 'chunks', ['category'], unique=False)
    op.create_unique_constraint('uq_chunk_per_doc', 'chunks', ['document_id', 'chunk_index'])
    op.add_column('documents', sa.Column('doc_type', sa.String(length=128), nullable=False))
    op.add_column('documents', sa.Column('auto_tagged_fields', sa.JSON(), nullable=False))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_documents_file_hash', table_name='documents')
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.create_index('ix_documents_file_hash', 'documents', ['file_hash'], unique=False)
    op.drop_column('documents', 'indexed_at')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'auto_tagged_fields')
    op.drop_column('documents', 'doc_type')
    op.drop_constraint('uq_chunk_per_doc', 'chunks', type_='unique')
    op.drop_index(op.f('ix_chunks_category'), table_name='chunks')
    op.drop_column('chunks', 'image_paths')
    op.drop_column('chunks', 'phase')
    op.drop_column('chunks', 'category')
    op.drop_index(op.f('ix_index_jobs_document_id'), table_name='index_jobs')
    op.drop_table('index_jobs')
    # ### end Alembic commands ###
